	--	** BÀI TẬP 1 **--

 --******QUAN LY BAN HANG****** --

CREATE DATABASE QuanLyBanHang

USE QuanLyBanHang

CREATE TABLE KHACHHANG(
	MAKH CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),
	DCHI VARCHAR(50),
	SODT VARCHAR(20),
	NGSINH SMALLDATETIME,
	NGDK SMALLDATETIME,
	DOANHSO MONEY,
)


CREATE TABLE NHANVIEN(
	MANV CHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),  
	SODT VARCHAR(20),
	NGVL SMALLDATETIME,
)


CREATE TABLE SANPHAM(
	MASP CHAR(4) NOT NULL PRIMARY KEY, 
	TENSP VARCHAR(40),
	DVT VARCHAR(20),
	NUOCSX VARCHAR(40),
	GIA MONEY,
)


CREATE TABLE HOADON(
	SOHD INT NOT NULL PRIMARY KEY,
	NGHD SMALLDATETIME,
	MAKH CHAR(4) ,
	MANV CHAR(4),
	TRIGIA MONEY,
)


CREATE TABLE CTHD(
	SOHD INT NOT NULL,
	MASP CHAR(4) NOT NULL,
	SL INT,
	PRIMARY KEY(SOHD,MASP)
)

	---TAO CAC KHOA NGOAI--
ALTER TABLE dbo.HOADON
ADD CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES dbo.KHACHHANG(MAKH)

ALTER TABLE dbo.HOADON
ADD CONSTRAINT FK_HD_NV FOREIGN KEY(MANV) REFERENCES dbo.NHANVIEN(MANV)

ALTER TABLE dbo.CTHD
ADD CONSTRAINT FK_CTHD_HD FOREIGN KEY(SOHD) REFERENCES dbo.HOADON(SOHD)

ALTER TABLE dbo.CTHD
ADD CONSTRAINT FK_CTHD_SP FOREIGN KEY(MASP) REFERENCES dbo.SANPHAM(MASP)





 --******QUẢN LÝ GIÁO VỤ****** --
 DROP DATABASE QuanLyGiaoVu

CREATE DATABASE QuanLyGiaoVu
USE QuanLyGiaoVu

CREATE TABLE HOCVIEN(
	MAHV CHAR(5) NOT NULL PRIMARY KEY,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3),
	NOISINH VARCHAR(40),
	MALOP CHAR(3),
)

CREATE TABLE GIAOVIEN(
	 MAGV CHAR(4) NOT NULL PRIMARY KEY,
	 HOTEN VARCHAR(40),
	 HOCVI VARCHAR(10),
	 HOCHAM VARCHAR(10),
	 GIOITINH VARCHAR(3),
	 NGSINH SMALLDATETIME,
	 NGVL SMALLDATETIME,
	 HESO NUMERIC(4,2),
	 MUCLUONG MONEY,
	 MAKHOA VARCHAR(4)
)

CREATE TABLE GIANGDAY(
	MALOP CHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV CHAR(4),
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,

	PRIMARY KEY(MALOP,MAMH)
)

CREATE TABLE KHOA (
	MAKHOA VARCHAR(4) NOT NULL PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)

CREATE TABLE MONHOC(
	MAMH VARCHAR(10) NOT NULL PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)

CREATE TABLE DIEUKIEN(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL,
	PRIMARY KEY(MAMH,MAMH_TRUOC)
)

CREATE TABLE LOP(
	MALOP CHAR(3) NOT NULL PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT,
	MAGVCN CHAR(4),
)

CREATE TABLE KETQUATHI(
	MAHV CHAR(5) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LANTHI TINYINT NOT NULL,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KQUA VARCHAR(10),

	PRIMARY KEY(MAHV,MAMH,LANTHI)
)


	--- TAO CAC KHOA NGOAI ---
ALTER TABLE MONHOC 
	ADD CONSTRAINT FK_MH_K FOREIGN KEY(MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE GIAOVIEN
	ADD CONSTRAINT FK_GV_K FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)

ALTER TABLE HOCVIEN
	ADD CONSTRAINT FK_HV_L FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

ALTER TABLE DIEUKIEN
	ADD CONSTRAINT FK_DK_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN
	ADD CONSTRAINT FK_DK_MHT FOREIGN KEY(MAMH_TRUOC) REFERENCES MONHOC(MAMH)

ALTER TABLE LOP
	ADD CONSTRAINT FK_L_HV FOREIGN KEY (TRGLOP) REFERENCES HOCVIEN(MAHV)

ALTER TABLE LOP
	ADD CONSTRAINT FK_L_GV FOREIGN KEY (MAGVCN) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE HOCVIEN
	ADD CONSTRAINT FK_HV_L1 FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY
	ADD CONSTRAINT FK_GD_L FOREIGN KEY(MALOP) REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY
	ADD CONSTRAINT FK_GD_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY
	ADD CONSTRAINT FK_GD_GV FOREIGN KEY(MAGV) REFERENCES GIAOVIEN(MAGV)

ALTER TABLE KETQUATHI
	ADD CONSTRAINT FK_KQT_MH FOREIGN KEY(MAMH) REFERENCES MONHOC(MAMH)

ALTER TABLE KETQUATHI
	ADD CONSTRAINT FK_KQT_HV FOREIGN KEY(MAHV) REFERENCES HOCVIEN(MAHV)


--Thêm vào 3 thuộc tính GHICHU, DIEMTB, XEPLOAI cho quan hệ HOCVIEN.--
ALTER TABLE HOCVIEN
	ADD GHICHU VARCHAR(20)
ALTER TABLE HOCVIEN
	ADD DIEMTB NUMERIC(4,2)
ALTER TABLE HOCVIEN
	ADD XEPLOAI CHAR(5)



			--* BÀI TẬP 2 *--
	--***** QUẢN LÝ BÁN HÀNG *****--

USE QuanLyBanHang

--CÂU 2: Thêm vào thuộc tính GHICHU có kiểu dữ liệu varchar(20) cho quan hệ SANPHAM.
ALTER TABLE dbo.SANPHAM
	ADD GHICHU VARCHAR(20)

--CÂU 3: Thêm vào thuộc tính LOAIKH có kiểu dữ liệu là tinyint cho quan hệ KHACHHANG.
ALTER TABLE dbo.KHACHHANG
	ADD LOAIKH TINYINT

--CÂU 4: Sửa kiểu dữ liệu của thuộc tính GHICHU trong quan hệ SANPHAM thành varchar(100).
ALTER TABLE dbo.SANPHAM
	ALTER COLUMN  GHICHU VARCHAR(100)

--CÂU 5: Xóa thuộc tính GHICHU trong quan hệ SANPHAM.
ALTER TABLE dbo.SANPHAM
	DROP COLUMN GHICHU

--CÂU 6: Làm thế nào để thuộc tính LOAIKH trong quan hệ KHACHHANG 
	--có thể lưu các giá trị là: “Vang lai”, “Thuong xuyen”, “Vip”…
ALTER TABLE dbo.KHACHHANG
	ALTER COLUMN LOAIKH VARCHAR(20)

--CÂU 7: Đơn vị tính của sản phẩm chỉ
--  có thể là (“cay”,”hop”,”cai”,”quyen”,”chuc”)
ALTER TABLE dbo.SANPHAM
	ADD CONSTRAINT CK_DVT CHECK(DVT IN('cay','hop','cai','quyen','chuc'))

--CÂU 8: Giá bán của sản phẩm từ 500 đồng trở lên.
ALTER TABLE dbo.SANPHAM
	ADD CHECK(GIA >= 500)

--CÂU 9: Mỗi lần mua hàng, khách hàng phải mua ít nhất 1 sản phẩm.
ALTER TABLE dbo.CTHD
	ADD CONSTRAINT CK_CTHD_SL CHECK(SL > 0 )

--CÂU 10: Ngày khách hàng đăng ký là khách hàng thành viên 
-- phải lớn hơn ngày sinh của người đó.
ALTER TABLE dbo.KHACHHANG
	ADD CHECK(NGDK > NGSINH)


		 --*BÀI TẬP 3*--
	--***** QUẢN LÝ GIÁO VỤ *****--

USE QuanLyGiaoVu

--CÂU 2: Mã học viên là một chuỗi 5 ký tự, 3 ký tự đầu là mã lớp, 2 ký tự cuối cùng là số thứ tự học viên trong lớp. VD: “K1101”.
ALTER TABLE HOCVIEN 
	ADD CHECK(LEN(MAHV) = 5 AND LEFT(MAHV,3) = MALOP AND RIGHT(MAHV, 2) BETWEEN 00 AND 99);

--CÂU 3: Thuộc tính GIOITINH chỉ có giá trị là “Nam” hoặc “Nu”.
ALTER TABLE dbo.GIAOVIEN
	ADD CHECK(GIOITINH IN('Nam','Nu'))
ALTER TABLE dbo.HOCVIEN
	ADD CHECK(GIOITINH IN('Nam','Nu'))

--CÂU 4: Điểm số của một lần thi có giá trị
--từ 0 đến 10 và cần lưu đến 2 số lẽ (VD: 6.22).
ALTER TABLE dbo.KETQUATHI
	ADD CHECK(DIEM BETWEEN 0 AND 10)

--CÂU 5: Kết quả thi là “Dat” nếu điểm từ 5 đến 10  
-- và “Khong dat” nếu điểm nhỏ hơn 5
ALTER TABLE dbo.KETQUATHI
	ADD	CHECK((DIEM < 5 AND KQUA = 'Khong Dat') OR (DIEM >= 5 AND KQUA = 'Dat'))

--CÂU 6: Học viên thi tối đa 3 lần
ALTER TABLE dbo.KETQUATHI
	ADD CHECK(LANTHI <= 3)

--CÂU 7: Học kỳ chỉ có giá trị từ 1 đến 3
ALTER TABLE dbo.GIANGDAY
	ADD CHECK(HOCKY BETWEEN 1 AND 3)

--CÂU 8: Học vị của giáo viên chỉ có thể là “CN”, “KS”, “Ths”, ”TS”, ”PTS”.
ALTER TABLE dbo.GIAOVIEN
	ADD CHECK(HOCVI IN('CN','KS','Ths','TS','PTS'))

			---HẾT---